### ISSUE TITLE
Luigi's Mansion codes seem incorrect

### ISSUE THREAD

**Issue by ModestBitboard** [mutesplash/legomario#1]
As strange as it might be Lego has added a new header to some of the codes which goes BLUE RED instead of GREEN RED. This means some of the codes you put in might not work fully (In hex GREEN RED translates to 0x0 and BLUE RED Translates to 0x1). I haven't tested your codes to see if they still work but I just wanted to mention that. Also, a quick note that E Gadd's code (from set 71397) Will appear as 0x2, the same code as a goomba. If you need any of the hex codes I have a program on my computer which helps me collect them that I could send you (It's written in python 3).

**Comment by ModestBitboard** [comment]
I should also point out that there are multiple sets of codes but the important ones are the 4th and 5th. 4th is the code and 5th is the header so for a goomba it would be `0x2 0x0` but for E Gadd it would be `0x2 0x1` and for a flagpole, it is `0xb7 0x0`...

**Comment by mutesplash** [comment]
I noticed the new prefix and I have been kind of lazy to update the repo.  Most of my work has been done empirically and not by using a color-to-hex translation.  I just recently discovered [LEGO Mario Reverse Engineering](https://github.com/bricklife/LEGO-Mario-Revengl) and I need to take a look at that.

I have already added a Blue/Red path to my brute-force generator and printed out half of them to check against fw 5.1.  Since you noticed, I'll try and fix this up today.

I don't quite understand what you mean by E Gadd.  Do you mean [this part](https://brickset.com/parts/6389750/flat-tile-2x2-w-sticker-no-152)?  It looks like it might have a TEAL start, which is even more crazy.  Do you have it in hand to be sure?  If it's the same code as a goomba, that's not too surprising as other custom icons share code colors

**Comment by mutesplash** [comment]
I've updated the page with B/R support, see if this changes anything for you.  Going to check with the app to see if there's a firmware update now.

**Comment by mutesplash** [comment]
FW 5.1.03
Asset pack version 4 - 0 - 0 - 214
App version 2.3.1.11307 build 13617

No new codes

**Comment by ModestBitboard** [comment]
Thanks for responding! Yes, that is E Gadd. I have the first Luigi's mansion set and I can confirm that it is blue, not teal. I for one never thought that they would use a new header/preset so I had to spend a day debugging one of my python3 scripts until I saw the problem.

**Comment by mutesplash** [comment]
My code now prefers the GR prefixes when eliminating backwards duplicates.

So... BRGYP ... for that part, aka GRBPY?  It looks more like BRPYG, from that picture, though.  What does he do when you step on him?

**Comment by ModestBitboard** [comment]
When you scan the tile you get a character dialogue, not unlike Toad's... I also don't have a printer so I can't test your updated document but I can however tell you the colours of all Luigi's mansion codes.

**Comment by ModestBitboard** [comment]
E Gadd's code goes BRPYV (Blue Red Pink Yellow Violet).

**Comment by ModestBitboard** [comment]
FYI E. Gadd is the white-haired crazy goggles character from the first Luigi's mansion set.

**Comment by mutesplash** [comment]
I've printed the entire space and tested them.  That one checks out with your description.  I just wasn't sure if he was supposed to be an adversary or not.

Everything ok now?  Good to close?

**Comment by ModestBitboard** [comment]
Yeah, it's good to close. This script is truly amazing and I love using it on chrome as a database for the codes! But I do want to give you a quick suggestion in case you are willing to face a bit of a challenge... How 'bout a script that takes in two hex codes (A header and the main data) and generates a code for use? That would be a useful way to make custom codes that a computer connected to it could search for, it's just an idea.. If you don't want ot then I might make a python app to do that. But anyways thank you for updating your HTML script and I wish you and this project the best!

**Comment by mutesplash** [comment]
Hmm, I will try connecting to lego mario over bluetooth to verify these things.

**Comment by ModestBitboard** [comment]
You can use my python script to connect to lego Mario and detect the hex code of the barcode he scans. Check it out here: https://github.com/ShadowFire5650/legomario.git
It requires the Python package Bleak, just so you know...
I hope this is useful for future projects!

**Comment by mutesplash** [comment]
I wrote my own Mario Bluetooth connector with some ideas from yours in order to better understand how it works.  I don't quite understand how you got the subscribe byte array but I do understand the fourth byte.  😄 

The [reverse engineering page](https://github.com/bricklife/LEGO-Mario-Reveng) "how to decode" seems wrong, but the color "priority" seems correct.  The goomba is GRBPY.  B P Y would be 0 1 3
(30 x 0) + (5 x 1) + (1 x 3) + 1 = 9
But it's 0x2

The "mystery" color might be Green when used with a BR code.  Also BRPGY returns 0xFB 0x00 and does not have 0x01 as the second byte.  Something still to be solved here.

**Comment by ModestBitboard** [comment]
My library is a copy of [this](https://github.com/salendron/pyLegoMario) but with compatibility with the new codes and my own examples, patches to the code, and other stuff.. to be honest I don't even know what the subscribe byte array is but it works so I am not going to question it as I am not good with Bluetooth programming.

**Comment by mutesplash** [comment]
haha, I cracked it in an algorithmic way.  I can accurately predict from a code what the integer value will be.  Listed out all the codes from 2 (0x02 0x00) (GRBPY) to 420 (0xa5 0x1) (BRLVT).  I spent a lot of time trying to figure it out mathematically but I gave up.  I'll post some python code in this repo sometime soon.

**Comment by mutesplash** [comment]
Alright, posted.  See if that helps you in your adventures!

**Comment by ModestBitboard** [comment]
Words cannot describe how awesome this is, Keep up the good work! I will test this out later and get back to you on what I think...

**Comment by mutesplash** [comment]
It's in a kind-of end-user state now.  No more looking at debugging output.  You can register for events on a callback and process them easily.
